// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApplication.Data.Persistence;

namespace WebApplication.Data.Migrations
{
    [DbContext(typeof(WebApplicationDbContext))]
    partial class WebApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Data.Core.EntityModels.UserAccount", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("20000000-0000-0000-0000-000000000001"),
                            Email = "IsaacAlger@gmail.com",
                            PasswordHash = "TestHash",
                            Username = "IsaacAlger"
                        },
                        new
                        {
                            Guid = new Guid("20000000-0000-0000-0000-000000000002"),
                            Email = "IsaacAlger2@gmail.com",
                            PasswordHash = "TestHash2",
                            Username = "IsaacAlger2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
